### PR TITLE
[Help Page] Etcher cause its cool

### PR DESCRIPTION
**Pull request by MrDiamond123**
Replaced USBWriter with Etcher as its easy to use and cross compatable

### CODE REVIEW

**Comment by FriendsNone** [comment]
You know... It's better if this guide has instructions for Rufus, UNetbootin, other tools too

**Comment by MrDiamond123** [comment]
Etcher is Cross Platform though and is so easy to use
[Gif to show you](https://etcher.io/static/screenshot-1x.gif)

**Comment by MrDiamond123** [comment]
![Etcher Gif]
(https://etcher.io/static/screenshot-1x.gif)

**Comment by FriendsNone** [comment]
You'll never know if people want different tools ¯\_(ツ)_/¯

**Comment by MrDiamond123** [comment]
I still left the terminal options

**Comment by colorfulchair** [comment]
I don't see the point of this pull request, as USBwriter already works. Why replace it?

**Comment by MrDiamond123** [comment]
@aren-cllc Etcher is cross compatible but USBWriter is only for windows

**Comment by colorfulchair** [comment]
But then you would just use dd

**Comment by vicr123** [comment]
I'll have to test this before I merge it. Thanks for letting me know about this though.

**Comment by MrDiamond123** [comment]
@vicr123

**Comment by MrDiamond123** [comment]
@aren-cllc (WARNING MEME COMING)
Ain't nobody got time for that

**Comment by vicr123** [comment]
Ok I've tested Etcher and it seems to work. I'll probably merge this in a bit :)

**Comment by FriendsNone** [comment]
That took a month 😄

**Pull request closed without merging**
